name: client
description: "실시간 보이스피싱 탐지 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_overlay_window: ^0.5.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.0
  tflite_flutter: ^0.11.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/tokenizer.json
